import type { Metadata } from "next";
import { ArrowUpRight, Box, Building2, Factory, FileCheck2, Link2, MapPin, ShieldCheck, UserRound } from "lucide-react";
import { MonosFrame } from "../../components/monos-shell";
import { cloudyProduct } from "../../monos-data";

export const metadata: Metadata = { title: "B+ Furniture — Brand Profile — Monos", description: "Hồ sơ thương hiệu B+ Furniture và mối liên hệ với sản phẩm Cloudy." };

export default function BPlusBrandProfile() {
  return <MonosFrame active="brands">
    <article className="brand-profile-page">
      <section className="brand-profile-hero"><div className="brand-profile-copy"><div className="eyebrow muted"><FileCheck2 size={14} /> Brand Profile / 001</div><span className="brand-profile-status"><span /> Thông tin sản phẩm do brand cung cấp</span><h1>B+<br /><em>Furniture.</em></h1><p>Một thương hiệu furniture được ghi nhận qua cách Cloudy được giới thiệu: từ thông tin sản phẩm, thông số kỹ thuật đến các file thiết kế tải xuống.</p><div className="brand-profile-meta"><span><Building2 size={15} /> Thương hiệu furniture</span><span><MapPin size={15} /> Việt Nam</span><span><Factory size={15} /> Nhà máy chưa công bố</span></div></div><figure className="brand-profile-image"><img src={cloudyProduct.images[0].url} alt="Cloudy — sản phẩm được B+ Furniture giới thiệu" /><figcaption>Cloudy / product record của B+ Furniture</figcaption></figure></section>
      <section className="brand-profile-facts"><div><span>Vai trò</span><strong>Furniture brand</strong><small>Product development & presentation</small></div><div><span>Sản phẩm liên quan</span><a href="/objects/cloudy"><strong>Cloudy</strong></a><small>LC060 · Lounge chair</small></div><div><span>Designer</span><strong>Chưa công bố</strong><small>Không tự suy đoán từ nguồn brand</small></div><div><span>Nhà máy</span><strong>Chưa công bố</strong><small>Không gắn tên xưởng khi chưa có bằng chứng</small></div></section>
      <section className="brand-profile-section section-pad"><div><div className="eyebrow muted"><Box size={14} /> Brand record</div><h2>Brand là một<br /><em>lớp trung gian.</em></h2></div><div className="brand-profile-text"><p>Trong một hồ sơ sản phẩm, brand có thể là nơi công bố hình ảnh, thông số, file kỹ thuật và câu chuyện sản phẩm. Điều đó không đồng nghĩa brand là designer hay là nhà máy trực tiếp sản xuất.</p><a className="card-link" href={cloudyProduct.sourceUrl} target="_blank" rel="noreferrer">Mở nguồn B+ Furniture <ArrowUpRight size={15} /></a></div></section>
      <section className="brand-profile-connection section-pad"><div className="eyebrow muted"><Link2 size={14} /> Relationship record</div><h2>Những gì đã nối<br /><em>và những gì còn mở.</em></h2><div className="brand-connection-grid"><article><span>01 / Object</span><h3>Cloudy</h3><p>Hồ sơ sản phẩm chính thức được nối về B+ Furniture.</p><a className="card-link" href="/objects/cloudy">Mở hồ sơ đồ vật <ArrowUpRight size={15} /></a></article><article><span>02 / Designer</span><h3>Chưa công bố</h3><p>Monos chưa ghi tên designer cá nhân nếu nguồn công khai chưa xác nhận.</p><a className="card-link" href="/designers">Xem danh bạ designer <ArrowUpRight size={15} /></a></article><article><span>03 / Factory</span><h3>Không công bố</h3><p>Không hiển thị một nhà máy cụ thể để tránh biến suy đoán thành provenance.</p><a className="card-link" href="/factories">Xem danh bạ nhà máy <ArrowUpRight size={15} /></a></article></div></section>
      <section className="brand-profile-source section-pad"><div><div className="eyebrow light"><ShieldCheck size={14} /> Source status</div><h2>Minh bạch<br /><em>cả phần chưa biết.</em></h2></div><div><p>Nguồn chính của hồ sơ là trang sản phẩm Cloudy của B+ Furniture. Trạng thái “chưa công bố” chỉ nói rằng nguồn hiện có không xác nhận designer hoặc nhà máy; nó không phải kết luận rằng các bên đó không tồn tại.</p><div className="ganh-source-links"><a className="light-button" href={cloudyProduct.sourceUrl} target="_blank" rel="noreferrer">Mở nguồn brand <ArrowUpRight size={16} /></a><a className="light-button" href="/provenance">Xem nguyên tắc nguồn gốc <ArrowUpRight size={16} /></a></div></div></section>
      <div className="brand-profile-footnote section-pad"><UserRound size={15} /> Khi brand bổ sung hồ sơ designer hoặc nhà máy, Monos có thể nối thêm quan hệ mà không thay đổi hồ sơ sản phẩm.</div>
    </article>
  </MonosFrame>;
}
